=== OrcaBus/service-icav2-data-copy-manager/app/event-schemas/icav2-data-copy-sync.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "isUri": {
      "pattern": "^(icav2|s3)://[a-zA-Z0-9_-]*/[a-zA-Z0-9_/-]*"
    },
    "renamingMapObjectInput": {
      "type": "object",
      "oneOf": [
        {
          "properties": {
            "sourceUri": {
              "$ref": "#/$defs/isUri"
            }
          },
          "required": ["sourceUri"]
        },
        {
          "properties": {
            "dataId": {
              "type": "string",
              "minLength": 1
            }
          },
          "required": ["dataId"]
        }
      ]
    },
    "renamingMapObjectOutput": {
      "type": "object",
      "properties": {
        "outputFileName": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": ["outputFileName"]
    },
    "renamingMapObject": {
      "allOf": [
        { "$ref": "#/$defs/renamingMapObjectInput" },
        { "$ref": "#/$defs/renamingMapObjectOutput" }
      ]
    }
  },
  "description": "icav2-data-copy-sync External Event",
  "type": "object",
  "properties": {
    "EventBusName": {
      "type": "string",
      "enum": ["OrcaBusMain"],
      "minLength": 1
    },
    "Source": {
      "type": "string",
      "minLength": 1
    },
    "DetailType": {
      "type": "string",
      "minLength": 1,
      "enum": ["ICAv2DataCopySync"]
    },
    "Detail": {
      "type": "object",
      "properties": {
        "payload": {
          "type": "object",
          "properties": {
            "sourceUriList": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1,
                "$ref": "#/$defs/isUri"
              },
              "minItems": 1
            },
            "destinationUri": {
              "type": "string",
              "minLength": 1
            },
            "renamingMapList": {
              "type": "array",
              "items": {
                "$ref": "#/$defs/renamingMapObject"
              }
            },
            "externalSourceUriList": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1,
                "$ref": "#/$defs/isUri"
              }
            }
          },
          "required": ["sourceUriList", "destinationUri"]
        },
        "taskToken": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": ["payload", "taskToken"]
    }
  },
  "required": ["EventBusName", "Source", "DetailType", "Detail"]
}

=== OrcaBus/service-icav2-data-copy-manager/examples/external-event.json
{
  "EventBusName": "OrcaBusMain",
  "Source": "manual",
  "DetailType": "ICAv2DataCopySync",
  "Detail": {
    "payload": {
      "sourceUriList": [
        "s3://pipeline-dev-cache-503977275616-ap-southeast-2/byob-icav2/development/test_data/ora-testing/"
      ],
      "destinationUri": "s3://pipeline-dev-cache-503977275616-ap-southeast-2/byob-icav2/development/test_data_copy/"
    },
    "taskToken": "your-step-function-task-token"
  }
}
